// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void t() {
    driver.get("https://www.demo.guru99.com/V4/manager/addcustomerpage.php");
    driver.manage().window().setSize(new Dimension(1900, 1017));
    driver.findElement(By.id("dob")).click();
    driver.findElement(By.id("dob")).sendKeys("0002-01-01");
    driver.findElement(By.id("dob")).sendKeys("0020-01-01");
    driver.findElement(By.id("dob")).sendKeys("0200-01-01");
    driver.findElement(By.id("dob")).sendKeys("2001-01-01");
    driver.findElement(By.name("addr")).click();
  }
}
